import{a as S,S as L,i as u}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function c(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(e){if(e.ep)return;e.ep=!0;const i=c(e);fetch(e.href,i)}})();document.querySelector(".search-form"),document.querySelector(".search-input"),document.querySelector(".search-btn"),document.querySelector(".images-list"),document.querySelector(".loader"),document.querySelector(".more-button"),document.querySelector(".up-button");function q(r){return`<li class="images-list-item">
  <a class="img-link" href=${image.largeImageURL} onclick="event.preventDefault()"><img class="img" src=${image.webformatURL} alt=${image.tags}></img></a>
   <ul class="img-dscr">
      <li class="img-data">
        <p class="img-data-title">Likes</p>
        <p class="img-data-numbers">${image.likes}</p>
      </li>
      <li class="img-data">
        <p class="img-data-title">Views</p>
        <p class="img-data-numbers">${image.views}</p>
      </li>
      <li class="img-data">
        <p class="img-data-title">Comments</p>
        <p class="img-data-numbers">${image.comments}</p>
      </li>
      <li class="img-data">
        <p class="img-data-title">Downloads</p>
        <p class="img-data-numbers">${image.downloads}</p>
      </li>
    </ul>
</li>`}function w(r){return r.map(q).join(`
`)}document.querySelector(".search-form"),document.querySelector(".search-input"),document.querySelector(".search-btn"),document.querySelector(".images-list"),document.querySelector(".loader"),document.querySelector(".more-button"),document.querySelector(".up-button");async function g(r,o,c){try{return(await S.create({baseURL:"https://pixabay.com"}).get("/api/",{params:{key:"44431585-8d368e0ee08bb3db1ccb0f280",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:c}})).data}catch{console.log(enterError("","api get error"))}}const t={imageSearchForm:document.querySelector(".search-form"),imageSearchInput:document.querySelector(".search-input"),submitButton:document.querySelector(".search-btn"),imageList:document.querySelector(".images-list"),loader:document.querySelector(".loader"),more:document.querySelector(".more-button"),upBtn:document.querySelector(".up-button")},p=new L(".images-list-item a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250,animationSpeed:300,widthRatio:1,heightRatio:.95,disableRightClick:!0});let n="",s=1,h=1;const m=15;function v(){t.more.classList.remove("hidden")}function d(){t.more.classList.add("hidden")}function f(){t.loader.style.display="block"}function y(){t.loader.style.display="none"}function B(){t.imageSearchForm.scrollIntoView({behavior:"smooth"}),t.upBtn.setAttribute("hidden","")}function I(){window.scrollY>=50?t.upBtn.removeAttribute("hidden"):t.upBtn.setAttribute("hidden","")}t.imageSearchForm.addEventListener("submit",async r=>{if(r.preventDefault(),n=r.target.elements.userData.value.trim(),!n)return t.imageList.innerHTML="",u.info({message:"You need to enter search request!",position:"topRight",transitionIn:"bounceInDown",transitionOut:"fadeOutDown"});f(),d(),document.querySelector(".loader"),t.loader.style.display="block";const o=await g(n,s,m);if(o.hits.length===0)return t.imageList.innerHTML="",u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"bounceInDown",transitionOut:"fadeOutDown"});h=Math.ceil(o.totatlHits/m),p.refresh(),b(),y(),r.target.reset()});t.more.addEventListener("click",async()=>{s++,f(),d();const r=await g(n,s,m),o=w(r.hits);t.imageList.insertAdjacentHTML("beforeend",o),D(),p.refresh(),b(s,h),y()});function b(r,o){r>=o?(d(),u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",transitionIn:"bounceInDown",transitionOut:"fadeOutDown"})):v()}function D(){const r=t.imageList.children[0].getBoundingClientRect().height;scrollBy({top:r*3+48,behavior:"smooth"})}window.addEventListener("scroll",I);t.upBtn.addEventListener("click",B);
//# sourceMappingURL=commonHelpers.js.map
